Feat/no render json
platanus/rubocop-platanus pull request #4
Opened 2022-05-17 21:16 UTC by MrEarle

# Contexto

En Platanus todo el tiempo estamos cambiando herramientas, mejorando nuestras prácticas, etc. Esto ocasiona que los proyectos más viejos no reflejen nuestras últimas decisiones respecto de x temas. Para mantener cierto orden en el código, estamos utilizando [Rubocop](https://github.com/rubocop/rubocop). Esta gema define cientos de reglas de estilo que nos permite escribir código similar/entendible. La idea es crear reglas custom para impulsar decisiones que tomemos desde calidad dev.

En las APIs de Platanus por ahí se usa en los controllers `render json: {}`. Esto no es buena práctica porque al usar render json nos saltamos el uso de [ApiResponder](https://github.com/platanus/power_api#the-apiresponder) y los serializers. La consecuencia de esto es que si se cambia el adapter, el formato de la respuesta no variará en endpoints que usen render json.

De ser posible, también debería desalentarse el uso de `respond_with { some: "hash" }` porque, aunque funciona, tiene el mismo problema. En estos casos deberían usarse values y, a esos values, hacerles un serializer.

# Que se esta haciendo

Se crea una regla que muestra un warning cuando se usa `render json:` o se usa `respond_with` con un hash.

![image](https://user-images.githubusercontent.com/30664457/168909016-970ea733-b152-4cd5-9d8d-b5928c19b586.png)
![image](https://user-images.githubusercontent.com/30664457/168909050-be05dcc2-771a-4c0e-9a9b-f350a9a2651a.png)
![image](https://user-images.githubusercontent.com/30664457/168909194-8e49f6da-cef2-4ab2-ac38-c9d8bd19a3be.png)
![image](https://user-images.githubusercontent.com/30664457/168909217-509970fc-1c88-4571-b9f7-364a9fe35e4a.png)

2022-05-17 22:03 UTC, difernandez requested changes
Buena buena 🚀  dejé puros comentarios picky del comentario/documentación y una duda

2022-05-17 22:03 UTC, difernandez commented on lib/rubocop/cop/platanus/no_render_json.rb
> +      #     respond_with({ authorization_url: authorization_url })
falta un nivel de indentación acá

2022-05-17 22:03 UTC, difernandez commented on lib/rubocop/cop/platanus/no_render_json.rb
> +      #   end
acá quizás agregaría saltos de línea pa que se lea más fácil:
```ruby
      #   class Resource
      #     include ActiveModel::Serialization
      #
      #     attr_accessor :id, :name
      #
      #     def initialize(id, name)
      #       @id = id
      #       @name = name
      #     end
      #   end
```

2022-05-17 22:03 UTC, difernandez commented on lib/rubocop/cop/platanus/no_render_json.rb
> +      #     type :res
quizás poner `type :resource` pa que tenga el nombre de la clase

2022-05-17 22:03 UTC, difernandez commented on lib/rubocop/cop/platanus/no_render_json.rb
> +      #   # controllers/resources_controller.rb
si se va a usar un controler de api interna de ejemplo, pondría esa ruta: `controllers/api/internal/resources_controller.rb`

2022-05-17 22:03 UTC, difernandez commented on lib/rubocop/cop/platanus/no_render_json.rb
> +          (send nil? :respond_with (hash ...))
que rara esta sintáxis de pattern jaja creo que se entiende, pero una duda: detecta al `hash` si está definido en varias líneas? o en un método/variable? No es necesario que lo haga, pueden ser casos muy pelúos de detectar, pero me entró la duda

2022-05-20 14:43 UTC, MrEarle commented on lib/rubocop/cop/platanus/no_render_json.rb
> +          (send nil? :respond_with (hash ...))
Si. Rubocop representa el codigo como un Abstract Syntax Tree, asi que la parte de estilo del codigo la abstrae.

Pero ese patron no detecta si se llama con una variable. Solo funciona si se llama con un hash definido en el argumento mismo. Voy a agregar codigo para que detecte de la variable tambien 👌.

El problema es que puede ser bien complicado ver donde esta definida la variable (o simple y todavia no encuentro bien el metodo para hacerlo). Asi que por ahora solo voy a chequear si esta definida en el scope mas cercano.

Queda pendiente ver si se puede detectar en un scope mas lejano (como desde un metodo)

2022-05-20 14:45 UTC, MrEarle commented on lib/rubocop/cop/platanus/no_render_json.rb
> +          (send nil? :respond_with (hash ...))
Si sabes de una regla en rails que tambien mire las variables definidas a traves de metodos, avisame para sapear el codigo 🐸

2022-05-20 17:19 UTC, difernandez approved these changes
Crack, está bacán 👏

2022-05-23 13:31 UTC, merged